// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWwJmkfIqsj9IV1vxLJqwTakzAzhlieIw',
    appId: '1:822687329582:web:69eee00999f3700583debf',
    messagingSenderId: '822687329582',
    projectId: 'auth-7856a',
    authDomain: 'auth-7856a.firebaseapp.com',
    storageBucket: 'auth-7856a.appspot.com',
    measurementId: 'G-P145WXXVS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgjnk3gntztVuX4bghgwJtnV2Z1yQpjdk',
    appId: '1:822687329582:android:7c7eb1282a0e38ff83debf',
    messagingSenderId: '822687329582',
    projectId: 'auth-7856a',
    storageBucket: 'auth-7856a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhgavGL5LrxMF4sRhzJfj6J4iNJVfryNM',
    appId: '1:822687329582:ios:a6a59ad10582b2e383debf',
    messagingSenderId: '822687329582',
    projectId: 'auth-7856a',
    storageBucket: 'auth-7856a.appspot.com',
    iosBundleId: 'com.example.itawseel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhgavGL5LrxMF4sRhzJfj6J4iNJVfryNM',
    appId: '1:822687329582:ios:1d3c9ae1b62f548d83debf',
    messagingSenderId: '822687329582',
    projectId: 'auth-7856a',
    storageBucket: 'auth-7856a.appspot.com',
    iosBundleId: 'com.example.itawseel.RunnerTests',
  );
}
